### PR TITLE
Add headless rendering to the FAQ

### PR DESCRIPTION
**Pull request by asnt**
Document how to use vispy for headless rendering.

- [x] Identify the alternatives: Xvfb, osmesa, egl... (are they all linked?).
- [x] Document the requirements for each alternative. (EDIT: Minimal description.)

For another issue:
- [ ] Document the possibilities from inside a docker(/nvidia) container.

Related: vispy/vispy#1464, vispy/vispy#1602, vispy/vispy#1637, vispy/vispy#1684, vispy/vispy#1734, vispy/vispy#1718, vispy/vispy#1818, vispy/vispy#1848, vispy/vispy#1872
EGL:
https://docs.mesa3d.org/egl.html
https://stackoverflow.com/a/34444984

### CODE REVIEW

**Comment by asnt** [comment]
@djhoese This is a start with the info I have right now. To be tested and completed. Feel free to modify/complete.

**Comment by asnt** [comment]
From [this SO answer][pyopengl_headless] :
- Xvfb emulates an X server for rendering without display.
- EGL allows rendering without any X server. [[egl-1], [egl-2]]

[pyopengl_headless]: https://stackoverflow.com/a/55758789
[egl-1]: https://developer.nvidia.com/blog/linking-opengl-server-side-rendering/
[egl-2]: https://developer.nvidia.com/blog/egl-eye-opengl-visualization-without-x-server/

**Comment by djhoese** [comment]
This looks really good. I think the FAQ is a good place for this right now. In the future I think I'd like to restructure the documentation site as described in this presentation: https://youtu.be/t4vKPhjcMZg in which case this might be something that could be wrapped into a How-To or something. I'm still trying to fully understand the distinctions described there.

Do you think it would be worth adding the last two bullet points in your last comment above as information in the FAQ information?

**Comment by djhoese** [comment]
You could also link to that SO answer.

**Comment by djhoese** [comment]
When you think this is ready mark it as "Ready for review" and I'll re-review it and merge it. Thanks.

**Comment by asnt** [comment]
> When you think this is ready mark it as "Ready for review" and I'll re-review it and merge it. Thanks.

Sure @djhoese, whenever I get it to work. All solutions work for me except
- Xvfb with a PyQt5 backend (glfw/pyglet/osmesa are fine)
- EGL (through Mesa)

In both cases, it fails on `eglMakeCurrent()`. It might be something with my system.

Thank you for the suggestions and the link about the documentation above. This sounds like a good idea.

**Comment by asnt** [comment]
The issues I had are solved in vispy/vispy#2075.

@djhoese This is ready for review. It works on my side but on a desktop machine. Haven't tested with a truly headless system yet.

For the future: [Here](https://github.com/vispy/vispy/issues/2075#issuecomment-862342856) is a potential addition that would be needed to have EGL independent of X entirely.

**Review by djhoese — APPROVED** [review]
Looks good to me. Thanks.

**Pull request merged**
