### PR TITLE
Replace lena with astronaut picture.

### LINKED ISSUE #4: Usage of non-free lena picture
The source tree contains an occurrence of the infamous Lena picture located at `_static/screenshots/gloo-lena.png`, which is considered [non-free](https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html). Please consider replacing this image with a freely licensed alternative.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #4.

### CODE REVIEW

**Comment by larsoner** [comment]
I assume there are going to be related changes to vispy as well to match?

**Comment by ghisvail** [comment]
Just updating the commit-id of the submodule.

**Comment by larsoner** [comment]
Ahh, it should help if I merge this then :)

**Comment by larsoner** [comment]
...right?

**Comment by ghisvail** [comment]
indeed

**Pull request merged**
