### PR TITLE
FIX: print statements to functions

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Errors related to this are seen while trying to build on conda-forge.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@davidh-ssec JFTR: This is no showstopper for conda-forge. Those builds finish green.

**Comment by djhoese** [comment]
Honestly, I don't think this script is used anymore. I think this has been merged in to the `make/make.py` of the python vispy repository. I'm fine merging them. I'm guessing the git submodule needs to be updated and the PyPI package updated for conda-forge to recognize the change?

**Comment by kmuehlbauer** [comment]
@davidh-ssec I'm not up to date with the current vispy - website workflow. You are right, if we update the PyPi package, then we need to fix the recipy in `conda-forge`. So my suggestion is to just fix this here and have it in the next release.

**Comment by larsoner** [comment]
I didn't even know this script existed, @davidh-ssec if you didn't use it during the release process let's just remove it (it's always in the `git` history if for some reason we need to find it again later)

**Comment by djhoese** [comment]
It is called when you do `make publish` from this repository. I'll remove it in the PR I'm preparing. Currently trying to figure out if all the warnings I'm getting when generating the website happened previously. Might be something I work on for 0.5.1 to have the API docs actually link to the functions they reference.

**Comment by larsoner** [comment]
> Might be something I work on for 0.5.1 to have the API docs actually link to the functions they reference.

Assuming we're using `numpydoc` you should be able to adapt the SciPy function:

https://github.com/scipy/scipy/blob/master/doc/source/conf.py#L298

It's pretty straightforward, see an adapted one here:

https://github.com/mne-tools/mne-python/blob/master/doc/conf.py#L325

**Pull request merged**
