### PR TITLE
Nvidia switchable graphics instructions

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by djhoese** [comment]
So the switchable graphics don't automatically choose the powerful GPU? I guess that makes sense for battery life. So if I understand this correctly the Windows drivers make this a simple GUI option, the linux drivers aren't that advanced? I didn't realize there was so much information for this, maybe we should try to add a new doc page. I'll decide on that later.

I'll also have to try generating the documentation, I think you need a blank line under the section headers and after the code block declaration. Also I think it is "switchable" not "switcheable".

**Comment by hmaarrfk** [comment]
Bingo, you got it. This is really only true for laptops. I don't know how OSX does it.

Some people created extensions:
https://extensions.gnome.org/extension/985/optirun/

But nothing for the commandline that I know of.

**Comment by hmaarrfk** [comment]
I forgot how easy it was to generate these static websites. I got it running on my local machine and things seemed OK in terms of formatting.

screenshot from 2018-02-05 09-55-43

**Comment by djhoese** [comment]
Looks good, thanks. I'm asking a coworker about how to switch GPUs on OSX since he's done it before with VisPy and I think everything worked fine for him.

**Comment by hmaarrfk** [comment]
Awesome. Yeah, I think this would be great addition to the documentation.
I wonder how detachable graphics card are handled by the Windows/OSX. I
don't think they are very popular, but it is an interesting usecase.

I think that on windows, Nvidia's "game ready" drivers try to automatically
detect applications based on known games or maybe they do something smarter
like detect the % of the Intel GPU used for a certain app, and switch it
over to the Nvidia one the next run?

Can't wait to try IPython notebooks when you get around to documenting how
to do it.

**Comment by djhoese** [comment]
> Can't wait to try IPython notebooks when you get around to documenting how
to do it.

I can't wait either. I've been doing a lot of the debugging myself and if you are willing to do some javascript and webgl debugging it would be great to have someone help fully implement vispy in javascript. That is the first step to getting vispy fully supported in notebooks, then we get in to sending click events to javascript handlers instead of the python handlers which is a whole new can of worms.

**Comment by hmaarrfk** [comment]
Unfortunately, I'm a physics guy at heart, and don't know any javascript. I
don't think I would be much help :S.

**Comment by djhoese** [comment]
No problem. Turns out OSX does automatic switching between the GPUs (system preferences can turn off the switching).

**Comment by hmaarrfk** [comment]
Interesting. So whatever GPU you use is completely transparent to you?

What does  `print(vispy.sys_info())` say?

Without `primusrun`, on my Linux machine, I get:
```
GL version:  '3.0 Mesa 17.2.4'
MAX_TEXTURE_SIZE: 16384
```

**Comment by djhoese** [comment]
On my mid-2015 macbook:

```
GL version:  '2.1 ATI-1.60.26'
MAX_TEXTURE_SIZE: 16384
```

I'm not sure what makes it switch and I'm guessing that is Apple magic sauce that no one is supposed to know.

**Comment by hmaarrfk** [comment]
Maybe they just direct all OpenGL calls to the GPU.

On windows, the gpu doesn’t say it is in use while running spyder, but only
when running vispy.

**Pull request merged**
