### PR TITLE
Add code to do http redirect

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by almarklein** [comment]
Wait. Even better, I forgot that I already have a service running that handles redirects for several other domains. I'll just include it there.

**Comment by almarklein** [comment]
Done.

**Comment by kmuehlbauer** [comment]
@almarklein Works, thanks! And now we have also a pointer with this issue, how this works :grinning:

**Comment by almarklein** [comment]
For the record, I also have analytics (already see some people coming there via google), so we could see when the domain starts to phase out.

**Comment by djhoese** [comment]
That'd be great. @almarklein There were some google analytics enabled for the readthedocs and I think they were included in the original website code (don't feel like looking right now). Do you know who has ownership of that account? I've never used GA, but is there a decent alternative (free)? Or do you have an existing service that we could have others access? It'd be nice to get stats on which of the getting started guides people click on the most (once they are complete).

I'm not asking for handouts or trying to take advantage of stuff you may be paying for (anymore than you're already offering up) but just curious.

**Comment by almarklein** [comment]
I don't use GA anymore, but I just checked, and it looks like the GA tokens where from my account. You could just reset these to point to your own account if you want. GA if free, and I think since a while there is also an option to not let Google track your website users (or less so, anyway). I don't know any free alternatives.

The analytics I use is homegrown and running on the same server that hosts the website, so I cannot really use that for stuff hosted elsewhere.

**Pull request closed without merging**
